#ifndef HEADER_SYNCGAMEHEADER
#define HEADER_SYNCGAMEHEADER

#define SYNC_BUF_SIZE 32

typedef enum {
  SYNC_OPPONENT_LOST,
  SYNC_GAMESTART,
  SYNC_POSITION,
  SYNC_NO_POSITION,
  SYNC_ENDGAME
}SyncHeader;

#endif