#ifndef HEADER_SYNCGAME
#define HEADER_SYNCGAME

#define SYNC_BUF_SIZE 256

typedef enum {
  SYNC_GAMESTART,
  SYNC_SYNCSIGNAL,
  SYNC_PUTABLEPOS,
  SYNC_PUTPOSITION,
  SYNC_GAMEOVER,
  SYNC_GAMEOVER_FORCE
}SyncHeader;

extern int clientSockfd;

#endif